spring:
  datasource:
    url: jdbc:postgresql://my_postgres:5432/ratingDB
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: RatingService
server:
  port: 4569

ride-service:
  name: RideService
  url: http://RideService:4568/ride  
  path: /api/v1/ride                   

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      rideService:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 75
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3

