spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingDB
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: RatingService
server:
  port: 4569

ride-service:
  name: ride-service
  url: http://RideService:4568/ride

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
